/* GENERATED by tools/import-tracks.mjs — do not edit by hand. */
/* Metro resolves require() at build time, so every file is named literally. */

export const AUDIO: Record<string, number> = {
  "soft-open": require("../../assets/audio/soft-open.mp3"),
  "counter-run": require("../../assets/audio/counter-run.mp3"),
  "corner-table": require("../../assets/audio/corner-table.mp3"),
  "linen-and-oak": require("../../assets/audio/linen-and-oak.mp3"),
  "slow-counter": require("../../assets/audio/slow-counter.mp3"),
  "velvet-hours": require("../../assets/audio/velvet-hours.mp3"),
  "high-street": require("../../assets/audio/high-street.mp3"),
  "reading-room": require("../../assets/audio/reading-room.mp3"),
  "grey-light": require("../../assets/audio/grey-light.mp3"),
  "night-shift": require("../../assets/audio/night-shift.mp3"),
  "late-service": require("../../assets/audio/late-service.mp3"),
  "market-morning": require("../../assets/audio/market-morning.mp3"),
  "back-room": require("../../assets/audio/back-room.mp3"),
  "second-set": require("../../assets/audio/second-set.mp3"),
  "front-window": require("../../assets/audio/front-window.mp3"),
  "marble-floor": require("../../assets/audio/marble-floor.mp3"),
  "open-water": require("../../assets/audio/open-water.mp3"),
  "low-ceiling": require("../../assets/audio/low-ceiling.mp3"),
  "brass-hour": require("../../assets/audio/brass-hour.mp3"),
  "paper-lanterns": require("../../assets/audio/paper-lanterns.mp3"),
  "steam-and-tin": require("../../assets/audio/steam-and-tin.mp3"),
  "closing-time": require("../../assets/audio/closing-time.mp3"),
  "saturday-rush": require("../../assets/audio/saturday-rush.mp3"),
  "quiet-hall": require("../../assets/audio/quiet-hall.mp3"),
};
