import { LinearGradient } from "expo-linear-gradient";
import { Image, View } from "react-native";

import { COVERS } from "../data/covers";
import { hashAngle } from "../lib/format";
import { BRAND, RADIUS } from "../theme/tokens";

/**
 * Tracks, playlists and moods show the placeholder art generated by
 * tools/generate-covers.mjs. An id without an image falls back to the
 * old deterministic face: the brand gradient rotated by a hash of its id,
 * with a few of its own waveform peaks drawn over it.
 */
export function Cover({
  id,
  peaks,
  size,
  radius,
  bars = 11,
}: {
  id: string;
  peaks?: number[];
  size: number;
  radius?: number;
  bars?: number;
}) {
  const art = COVERS[id];
  if (art !== undefined) {
    return (
      <Image
        source={art}
        style={{ width: size, height: size, borderRadius: radius ?? Math.round(size * 0.22) }}
      />
    );
  }

  const angle = hashAngle(id);
  const rad = (angle * Math.PI) / 180;
  const start = { x: 0.5 - Math.cos(rad) / 2, y: 0.5 - Math.sin(rad) / 2 };
  const end = { x: 0.5 + Math.cos(rad) / 2, y: 0.5 + Math.sin(rad) / 2 };

  /* Take `bars` evenly spaced peaks so a 48 px cover and a 280 px cover
     show the same shape at different densities. */
  const picked: number[] = [];
  if (peaks?.length) {
    const step = peaks.length / bars;
    for (let i = 0; i < bars; i += 1) picked.push(peaks[Math.floor(i * step)] ?? 0);
  }

  const gap = Math.max(1, size * 0.018);
  const barWidth = Math.max(1.5, (size * 0.62 - gap * (bars - 1)) / bars);

  return (
    <LinearGradient
      colors={[BRAND[0], BRAND[1], BRAND[2]]}
      start={start}
      end={end}
      style={{
        width: size,
        height: size,
        borderRadius: radius ?? Math.round(size * 0.22),
        overflow: "hidden",
        alignItems: "center",
        justifyContent: "flex-end",
        paddingBottom: size * 0.19,
      }}
    >
      {picked.length > 0 && (
        <View style={{ flexDirection: "row", alignItems: "flex-end", gap }}>
          {picked.map((p, i) => (
            <View
              key={i}
              style={{
                width: barWidth,
                height: Math.max(barWidth, size * 0.42 * (0.25 + p * 0.75)),
                borderRadius: barWidth,
                backgroundColor: "rgba(255,255,255,0.92)",
              }}
            />
          ))}
        </View>
      )}
    </LinearGradient>
  );
}

/** The logo mark on its own — four bars, used in headers. */
export function Mark({ size = 22 }: { size?: number }) {
  const heights = [1, 0.68, 0.48, 0.34];
  const w = Math.max(2, size * 0.13);
  return (
    <View style={{ flexDirection: "row", alignItems: "center", gap: w * 0.7, height: size }}>
      {heights.map((h, i) => (
        <LinearGradient
          key={i}
          colors={[BRAND[0], BRAND[2]]}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
          style={{ width: w, height: size * h, borderRadius: RADIUS.pill }}
        />
      ))}
    </View>
  );
}
