/* Generates supabase/seed.sql from PLANS in lib/pricing.ts. Run it after any
   change to a plan; test/plans-seed.test.ts fails until you do. */
import { writeFileSync } from "node:fs";
import { PLANS } from "../lib/pricing.ts";
import { STREAMING_MONTHLY_DEFAULT } from "../lib/rates.ts";

const json = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'`;
const text = (v) => `'${String(v).replace(/'/g, "''")}'`;

const rows = PLANS.map(
  (p, i) =>
    `(${text(p.id)}, ${text(p.name)}, ${Math.round(p.monthly * 100)}, ` +
    `${p.maxM2 === null ? "null" : p.maxM2}, ${json(p.tagline)}, ${json(p.features)}, ${i + 1}, true)`,
).join(",\n");

writeFileSync(
  new URL("../supabase/seed.sql", import.meta.url),
  `-- GENERATED by scripts/plans-seed.mjs - do not edit by hand.
insert into plans (id, name, monthly_ore, max_m2, tagline, features, sort, active) values
${rows}
on conflict (id) do nothing;

insert into addons (id, name, monthly_ore, active) values
('streaming', '{"da":"Streaming","en":"Streaming"}', ${STREAMING_MONTHLY_DEFAULT * 100}, true)
on conflict (id) do nothing;
`,
);
