#!/usr/bin/env node
/* ====================================================================
 *  Import the catalogue from the Odatone website into the app.
 *
 *  The website is the single source of truth for tracks (lib/tracks.ts).
 *  This script reads that file, writes a mobile-shaped copy into
 *  src/data/tracks.ts, and writes the static require() map the React
 *  Native bundler needs (src/audio/assets.ts) — Metro cannot resolve a
 *  require() built from a string at runtime, so every file has to be
 *  named literally somewhere.
 *
 *  It also copies the mp3s into assets/audio/.
 *
 *  Usage, from the app root:
 *      node tools/import-tracks.mjs [path-to-website]
 *  Default website path: .. (the repository root this app lives in)
 *
 *  Peaks are downsampled from 180 buckets to 64 — a phone-width
 *  waveform cannot show more, and 24 × 180 floats is dead weight in
 *  the JS bundle.
 * ==================================================================== */

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, readdirSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const APP = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = resolve(APP, process.argv[2] ?? "..");
const PEAK_BUCKETS = 64;

const src = join(SITE, "lib", "tracks.ts");
if (!existsSync(src)) {
  console.error(`\n  Cannot find ${src}\n  Pass the website folder: node tools/import-tracks.mjs <path>\n`);
  process.exit(1);
}

const file = readFileSync(src, "utf8");

/* The TRACKS array, sliced out by its own literal boundaries. */
const start = file.indexOf("export const TRACKS: Track[] = [");
if (start < 0) throw new Error("TRACKS array not found — has lib/tracks.ts been restructured?");
const body = file.slice(file.indexOf("[", start), file.indexOf("\n];", start) + 2);

const field = (chunk, name, re) => {
  const m = chunk.match(re);
  if (!m) throw new Error(`field "${name}" missing from a track entry`);
  return m[1];
};

const tracks = [];
for (const chunk of body.split(/\n  \{\n/).slice(1)) {
  const peaks = JSON.parse(field(chunk, "peaks", /peaks: (\[[^\]]*\])/));
  const step = peaks.length / PEAK_BUCKETS;
  const small = Array.from({ length: PEAK_BUCKETS }, (_, i) => {
    const slice = peaks.slice(Math.floor(i * step), Math.max(Math.floor((i + 1) * step), Math.floor(i * step) + 1));
    return Math.round(Math.max(...slice, 0) * 100) / 100;
  });
  tracks.push({
    id: field(chunk, "id", /id: "([^"]+)"/),
    title: {
      da: field(chunk, "title.da", /title: \{ da: "([^"]+)"/),
      en: field(chunk, "title.en", /title: \{ da: "[^"]+", en: "([^"]+)"/),
    },
    artist: field(chunk, "artist", /artist: "([^"]+)"/),
    genre: field(chunk, "genre", /genre: "([^"]+)"/),
    mood: field(chunk, "mood", /mood: "([^"]+)"/),
    bpm: Number(field(chunk, "bpm", /bpm: ([\d.]+)/)),
    vox: field(chunk, "vox", /vox: (true|false)/) === "true",
    energy: Number(field(chunk, "energy", /energy: ([\d.]+)/)),
    duration: Number(field(chunk, "duration", /duration: ([\d.]+)/)),
    file: field(chunk, "src", /src: "\/audio\/([^"]+)"/),
    peaks: small,
  });
}
if (!tracks.length) throw new Error("parsed 0 tracks");

/* ---- assets/audio ---- */
const audioOut = join(APP, "assets", "audio");
mkdirSync(audioOut, { recursive: true });
let copied = 0;
for (const t of tracks) {
  const from = join(SITE, "public", "audio", t.file);
  if (existsSync(from)) { copyFileSync(from, join(audioOut, t.file)); copied += 1; }
  else console.warn(`  ! missing audio file: ${t.file}`);
}

/* ---- src/audio/assets.ts ---- */
const present = new Set(readdirSync(audioOut));
mkdirSync(join(APP, "src", "audio"), { recursive: true });
writeFileSync(
  join(APP, "src", "audio", "assets.ts"),
  `/* GENERATED by tools/import-tracks.mjs — do not edit by hand. */
/* Metro resolves require() at build time, so every file is named literally. */

export const AUDIO: Record<string, number> = {
${tracks.filter((t) => present.has(t.file)).map((t) => `  "${t.id}": require("../../assets/audio/${t.file}"),`).join("\n")}
};
`,
  "utf8",
);

/* ---- src/data/tracks.ts ---- */
mkdirSync(join(APP, "src", "data"), { recursive: true });
const entries = tracks
  .map(
    (t) => `  {
    id: "${t.id}",
    title: { da: "${t.title.da}", en: "${t.title.en}" },
    artist: "${t.artist}",
    genre: "${t.genre}",
    mood: "${t.mood}",
    bpm: ${t.bpm},
    vox: ${t.vox},
    energy: ${t.energy},
    duration: ${t.duration},
    peaks: [${t.peaks.join(",")}],
  },`,
  )
  .join("\n");

writeFileSync(
  join(APP, "src", "data", "tracks.ts"),
  `/* GENERATED by tools/import-tracks.mjs from the website's lib/tracks.ts.
 *
 *  ⚠️  THE AUDIO IS PLACEHOLDER MATERIAL — synthesised, not Odatone's
 *  catalogue, and every artist name is invented. Re-run the import once
 *  the real files are in the website's public/audio.
 */

import type { Genre, Mood, L10n } from "../types";

export type Track = {
  id: string;
  title: L10n;
  artist: string;
  genre: Genre;
  mood: Mood;
  bpm: number;
  vox: boolean;
  /** 1 = barely there, 5 = drives the room. */
  energy: number;
  /** Seconds. */
  duration: number;
  /** Normalised waveform peaks, ${PEAK_BUCKETS} buckets. */
  peaks: number[];
};

export const TRACKS_ARE_PLACEHOLDER = true;

export const TRACKS: Track[] = [
${entries}
];

export const trackById = (id: string): Track | undefined => TRACKS.find((t) => t.id === id);
`,
  "utf8",
);

console.log(`  ${tracks.length} tracks imported, ${copied} audio files copied, peaks downsampled to ${PEAK_BUCKETS}.`);
